global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alerting rules
rule_files:
  - "alerts.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # tops-worker metrics
  - job_name: 'tops-worker'
    static_configs:
      - targets: ['tops-worker:8082']
    metrics_path: '/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true

  # tops-verifier metrics (if it had metrics)
  - job_name: 'tops-verifier'
    static_configs:
      - targets: ['verifier:8081']
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
