apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment-worker.yaml
  - deployment-verifier.yaml
  - service-worker.yaml
  - service-verifier.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app: tops-worker
  version: v1.0.0
