name: Deploy

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed
    branches: [main, master]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: staging
      url: https://staging.tops-worker.example.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to staging
        run: |
          echo "Deploying to staging environment..."
          # Example deployment commands:
          # kubectl apply -f k8s/staging/
          # docker-compose -f docker-compose.staging.yml up -d
          echo "Staging deployment completed successfully"

      - name: Run smoke tests
        run: |
          echo "Running smoke tests..."
          # Add your smoke test commands here
          # curl -f https://staging.tops-worker.example.com/health
          echo "Smoke tests passed"

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: production
      url: https://production.tops-worker.example.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to production
        run: |
          echo "Deploying to production environment..."
          # Example deployment commands:
          # kubectl apply -f k8s/production/
          # docker-compose -f docker-compose.production.yml up -d
          echo "Production deployment completed successfully"

      - name: Run health checks
        run: |
          echo "Running health checks..."
          # Add your health check commands here
          # curl -f https://production.tops-worker.example.com/health
          echo "Health checks passed"

      - name: Notify deployment success
        run: |
          echo "Production deployment successful!"
          # Add notification logic (Slack, email, etc.)
